import { dir } from 'i18next'
import { languages } from '../i18n/settings'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export async function generateStaticParams () {
  return languages.map((lng) => ({lng}))
}
 
export default function RootLayout({ 
  children,
  params: {
    lng
  }
}) {
 return (
    <html lang={lng} dir={dir(lng)}>
      <body>{children}</body>
    </html>
  )
}
